// import './globals.css'
import { Inter } from 'next/font/google'
import { Navigation } from "@/components/Navigation"; //other form
//import { Navigation } from "../components/Navigation";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My first Nextjs App',// Title html 
  description: 'Generated by Kenny Robert',
  keywords: 'next, react, app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
        <link
          rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/flatly/bootstrap.min.css"
        />
      </head>
      <body>

        {/* <h1>Navigation</h1>
        <ul>
          <li><a href="/about">about</a></li>
          <li><Link href="/about">about</Link></li> //recomend this not reload
        </ul> */}

        <Navigation/>
        <div className="container p-4">{children}</div>
        </body>
    </html>
  )
}
